//
// Generated file, do not edit! Created by nedtool 5.6 from delaybasedforwarding/linklayer/contract/randomDropHeader/RandomDropHeader.msg.
//

#ifndef __DELAYBASEDFORWARDING_RANDOMDROPHEADER_M_H
#define __DELAYBASEDFORWARDING_RANDOMDROPHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/common/packet/chunk/FieldsChunk.h"
// }}


namespace delaybasedforwarding {

/**
 * Class generated from <tt>delaybasedforwarding/linklayer/contract/randomDropHeader/RandomDropHeader.msg:24</tt> by nedtool.
 * <pre>
 * class RandomDropHeader extends inet::FieldsChunk
 * {
 *     chunkLength = B(4);
 *     uint32_t drop;
 * }
 * </pre>
 */
class RandomDropHeader : public ::inet::FieldsChunk
{
  protected:
    uint32_t drop;

  private:
    void copy(const RandomDropHeader& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RandomDropHeader&);

  public:
    RandomDropHeader(const char *name=nullptr);
    RandomDropHeader(const RandomDropHeader& other);
    virtual ~RandomDropHeader();
    RandomDropHeader& operator=(const RandomDropHeader& other);
    virtual RandomDropHeader *dup() const override {return new RandomDropHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint32_t getDrop() const;
    virtual void setDrop(uint32_t drop);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RandomDropHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RandomDropHeader& obj) {obj.parsimUnpack(b);}

} // namespace delaybasedforwarding

#endif // ifndef __DELAYBASEDFORWARDING_RANDOMDROPHEADER_M_H

